"""init

Revision ID: b4110ec062cf
Revises: None
Create Date: 2016-01-12 22:04:19.085359

"""

# revision identifiers, used by Alembic.
revision = 'b4110ec062cf'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yy_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_name', sa.Text(), nullable=True),
    sa.Column('option_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('option_name')
    )
    op.create_table('yy_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('open_id', sa.Text(), nullable=True),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('user_pass', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('yy_users')
    op.drop_table('yy_options')
    ### end Alembic commands ###
